// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEBodyPlanet.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20230523031432_act01")]
    partial class act01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CEBodyPlanet.Models.Ciudad", b =>
                {
                    b.Property<int>("Id_Ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ciudad"));

                    b.Property<int>("CodPostal")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Ciudad");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("CEBodyPlanet.Models.Persona", b =>
                {
                    b.Property<int>("Id_Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Persona"));

                    b.Property<string>("Apellido_Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CiudadId_Ciudad")
                        .HasColumnType("int");

                    b.Property<int>("DNI_Persona")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio_Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Ciudad")
                        .HasColumnType("int");

                    b.Property<string>("Mail_Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre_Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono_Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Persona");

                    b.HasIndex("CiudadId_Ciudad");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("CEBodyPlanet.Models.Persona", b =>
                {
                    b.HasOne("CEBodyPlanet.Models.Ciudad", "Ciudad")
                        .WithMany("Persona")
                        .HasForeignKey("CiudadId_Ciudad");

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("CEBodyPlanet.Models.Ciudad", b =>
                {
                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
